apiVersion: v1
kind: Namespace
metadata:
  name: bootc-vms
  labels:
    # Required for OpenShift to allow KubeVirt/CDI privileged workloads in this namespace
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
