---
all:
  hosts:
    sno:
      ansible_host: https://api.waba-sno.adc.lan:6443   # e.g. api.your-cluster.example.com
      ansible_connection: local                 # kubectl/oc runs locally against the cluster
